### ISSUE TITLE
Best way to reuse/cache ServiceInstance?

### ISSUE THREAD

**Issue by ghost** [yavijava/yavijava#230]
In my program I was getting multiple ServiceInstances from multiple vcenter/ESXi hosts, I'd like to cache the ServiceInstance somewhere and reuse later so I don't need to create a serviceInstance again. What's the best practice to do it that handles thread-safe as well? Thanks in advance.

**Comment by michaelrice** [comment]
Thats a rather first world problem.. You could do a lot of things to store the service instance in a cache, how you choose to do it is up to you. Just keep in mind that the sessions are only valid for like 30 mins by default. I dont remember what happens when you try to use an expired session but it wouldn't take long to find that out then make sure you handle that failure by renewing the session then updating your cache with the new valid session.

**Comment by ghost** [comment]
Thanks @michaelrice I am using some timeout cache for reusing the instance now.

**Comment by goalidea** [comment]
> Thanks @michaelrice I am using some timeout cache for reusing the instance now.

@michaelrice how to refresh session when session is time out?
