### ISSUE TITLE
VI java API's

### ISSUE THREAD

**Issue by purnanandkumar7** [yavijava/yavijava#266]
Does all the VI java API's are exposed in YAVI java or i have to use YAVI java API's only?

**Comment by michaelrice** [comment]
I do not understand this question. What do you mean?

**Comment by vThinkBeyondVM** [comment]
Old VIJava support was up to 5.5 and later since Vi Java was dead, Michael forked existing Vi Java project and renamed it as YA VI Java, which supports vSphere 6.0 as well..overall everything from older Vi Java is already there in yavi Java, hence use ya Vi Java. Your older code should work fine on ya Vi java

**Comment by purnanandkumar7** [comment]
Thanks @vThinkBeyondVM
