### ISSUE TITLE
VMware vCloud Director support

### ISSUE THREAD

**Issue by gionn** [yavijava/yavijava#41]
Hi,
we are looking for a decent java library to consume the vcloud REST API, what is the current support in this project?

If needed, we can work on it.

Thanks!

**Comment by michaelrice** [comment]
Hello @gionn vCloud Director is not part of vSphere and has its own REST based API. This project is only for vSphere APIs and currently only supports the SOAP Web Services API. I have other branches where I plan to add other vSphere APIs like the SSO, SMS, etc.. but have not done the work on those yet.

VMWare supplies a JAVA SDK for vCloud Director and I have used it. It works fine. Is there a reason you cant use it? Im guessing it must be due to licensing and your need to redistribute?

**Comment by michaelrice** [comment]
Hi @gionn since you have never responded again Im just going to close this out.

**Comment by gionn** [comment]
Hi @michaelrice,

I missed your reply, sorry for that.

The problems that arise with the official SDK are many, and the biggest hits for me are the lack of sources and the absence of abstraction on the SDK API (I've lost countless hours figuring how to retrieve a particular piece of information, having as unique help a huge PDF written a decade ago).

For this reason I was looking around to search some alternative, and I've hit in this repo, but I didn't understand which API it were implementing.

Thanks for the info.

Cheers.

**Comment by michaelrice** [comment]
Have you looked at jclouds? It may have support..

**Comment by gionn** [comment]
Yeah, they supported vcloud, then no one was actively maintaining it, and then they dropped the support from a recent release.

http://mail-archives.apache.org/mod_mbox/jclouds-user/201411.mbox/%3CCABoR60JOYeoff_psgf2X_VcvYDCro81-wLgm0NGR9mPk+qetcQ@mail.gmail.com%3E
